# *********************************************************************
# *************                 IAG                       *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in environment 
# usage architecture reference workflow

# currently it is only possible to configure 
# two types of languages "java and angular"
# this example use java
#
name: CI
on:
    workflow_dispatch:
#  pull_request:
    # Sequence of patterns matched against refs/heads
#    branches: [ main, develop ]
env:
  PROJECT: "best-practice"
  LENGUAGE: "java"
  ENVIROMENT_DEV: "development"
  ENVIROMENT_DEV_PREFIX: "dev"
  ENVIROMENT_INT: "integration"
  ENVIROMENT_INT_PREFIX: "int"
  SCANCODE_ALLOW: false
  SONAR_HOST: ""
  SONAR_USER: ""
  SONAR_TOKEN: ""
  SONAR_CL_VER: ""
  VULNERABILITY_HOST: ""
  VULNERABILITY_USER: ""
  VULNERABILITY_TOKEN: ""
jobs:
  cicd:
    runs-on: [ancillaries, build]
    steps:
        # checkout source code in runner 
        - name: Checkout source
          uses: actions/checkout@v2
        # checkout source workflow action base in runner   
        - name: Checkout actions
          uses: actions/checkout@v2
          with:
            repository: 'Iberia-Ent/software-engineering--reference-architecture--workflow'
            token: ${{ secrets.TOKEN_REP }}
            ref: 'main'
            path: '.github/cicd'
        # Configure step build process    
        - name: build
          id: output-build
          uses: ./.github/cicd/github_actions/build
          with:
              project_name: ${{ env.PROJECT }}
              lenguage-code: ${{ env.LENGUAGE }}
              aws-access-key: ${{secrets.AWS_ACCESS_KEY}} 
              aws-secret-acesss-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              # active true repositorio codeartifact - required: true - default: false (nexus adopt)      
              # user registry artifact - if codeArtifact allow then user is owner aws id.
              codeartifact-allow: true
              repository-user: ${{secrets.CODEARTIFACT_OWNER}}                
              ### Disable because is codeArtifact
              # repository-host:  ${{secrets.nexus_url}}                  
              # repository-token: ${{secrets.nexus_key}}
        # Configure step scan code process
        - name: scan
          uses: ./.github/cicd/github_actions/scan
          with:
              project_name: ${{ env.PROJECT }}
              lenguage-code: ${{ env.LENGUAGE }}
              service_name: ${{ steps.output-build.outputs.package-artifactid-name }}
              service_version: ${{ steps.output-build.outputs.package-version-name }}
              service_package: ${{ steps.output-build.outputs.package-type-name }}
              group_name: ${{ steps.output-build.outputs.package-groupid-name }}
              scancode-allow: ${{ env.SCANCODE_ALLOW }}
              sonarqube-host: ${{ env.SONAR_HOST }}
              sonarqube-user: ${{ env.SONAR_USER }}
              sonarqube-token: ${{ env.SONAR_TOKEN }}
              sonarqube-client-version: ${{ env.SONAR_CL_VER }}
              vulnerability-host: ${{ env.VULNERABILITY_HOST }}
              vulnerability-user: ${{ env.VULNERABILITY_USER }}
              vulnerability-token: ${{ env.VULNERABILITY_TOKEN }}
        # configure environment build process.
        - name: environment
          id: output-environment
          uses: ./.github/cicd/github_actions/environment
          with:
              project_name: ${{ env.PROJECT }}
              service_name: ${{ steps.output-build.outputs.package-artifactid-name }}
              group_name:   ${{ steps.output-build.outputs.package-groupid-name }}
              aws-access-key: ${{ secrets.AWS_ACCESS_KEY }} 
              aws-secret-acesss-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-environment-name: ${{ env.ENVIROMENT_INT }}
              aws-environment-prefix: ${{ env.ENVIROMENT_INT_PREFIX }}
              aws-environment-dev-name: ${{ env.ENVIROMENT_DEV }}
              aws-environment-dev-prefix: ${{ env.ENVIROMENT_DEV_PREFIX }}
        # configure deploy configure
        - name: deploy
          uses: ./.github/cicd/github_actions/deploy
          with:
              project_name: ${{ env.PROJECT }}
              lenguage-code: ${{ env.LENGUAGE }}
              aws-access-key: ${{secrets.AWS_ACCESS_KEY}} 
              aws-secret-acesss-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              service_name: ${{ steps.output-build.outputs.package-artifactid-name }}
              service_version: ${{ steps.output-build.outputs.package-version-name }}
              service_package: ${{ steps.output-build.outputs.package-type-name }}
              group_name: ${{ steps.output-build.outputs.package-groupid-name }}
              codeartifact-allow: true
              repository-user: ${{secrets.CODEARTIFACT_OWNER}}
              shared-number-ids-arn-suffix: ${{ steps.output-environment.outputs.shared-number-ids-arn-suffix }}
              security-group-number-ids: ${{ steps.output-environment.outputs.security-group-number-ids }}
              subnet-number-ids: ${{ steps.output-environment.outputs.subnet-number-ids }}
              alb-target-group-number-arn: ${{ steps.output-environment.alb-target-group-number-arn }}
              alb-target-group-number-arn-suffix: ${{ steps.output-environment.outputs.alb-target-group-number-arn-suffix }}
              lb-number-arn-suffix: ${{ steps.output-environment.outputs.lb-number-arn-suffix }}
              testIntegration-allow: false
              
