# *********************************************************************
# *************                 IAG                       *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in environment 
# usage architecture reference workflow

# currently it is only possible to configure 
# two types of languages "java and angular"
# this example use java
#
name: CI
on:
    workflow_dispatch:
#  pull_request:
    # Sequence of patterns matched against refs/heads
#    branches: [ main, develop ]
jobs:
  deploy:
    runs-on: [ancillaries]
    steps:
        - name: Checkout actions
          uses: actions/checkout@v2
          with:
            repository: 'Iberia-Ent/software-engineering--reference-architecture--workflow'
            token: ${{ secrets.TOKEN_REP }}
            ref: 'main'
            path: '.github/cicd'    
        - name: Deploy
          uses: ./.github/cicd/github_actions/deploy/test
          with:
              project-name: "best-practice"                                   # Product global name example: 'bestpratices' - require true, use in dns name
