# *********************************************************************
# *************                 IAG                       *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in environment 
# usage architecture reference workflow

# currently it is only possible to configure 
# two types of languages "java and angular"
# this example use java
#
name: CI
on:
    workflow_dispatch:
#  pull_request:
    # Sequence of patterns matched against refs/heads
#    branches: [ main, develop ]
jobs:
  deploy:
    runs-on: [ancillaries, build]
    steps:
        - name: Checkout source
          uses: actions/checkout@v2
        - name: Checkout actions
          uses: actions/checkout@v2
          with:
            repository: 'Iberia-Ent/software-engineering--reference-architecture--workflow'
            token: ${{ secrets.TOKEN_REP }}
            ref: 'main'
            path: '.github/cicd'
        - name: build
          uses: ./.github/cicd/github_actions/build
          with:
              project_name: "best-practice"
              lenguage-code: "java"
              aws-access-key: ${{secrets.AWS_ACCESS_KEY}} 
              aws-secret-acesss-key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
              codeartifact-allow: true # active true repositorio codeartifact - required: true - default: false (nexus adopt)
              repository-host:  ${{secrets.CODEARTIFACT_URL}}                  # host registry artifact - if codeArtifact allow then dns is example: my_domain-111122223333.d.codeartifact.us-west-2.amazonaws.com
              repository-user: ${{secrets.CODEARTIFACT_OWNER}}                # user registry artifact - if codeArtifact allow then user is owner aws id.
                  ### Disable because is codeArtifact
                # repository-token: ${{secrets.nexus_key}}
        # - name: clean
        #  shell: bash
        #  run: cd ${{ github.workspace }} && rm -rf *
