# *********************************************************************
# *************                 IAG                       *************
# *************       by Software Engineering             *************
# *********************************************************************
# This action yaml represents the different steps to perform 
# for a deployment in environment 
# usage architecture reference workflow

# currently it is only possible to configure 
# two types of languages "java and angular"
# this example use java
#
name: CI
on:
    workflow_dispatch:
#  pull_request:
    # Sequence of patterns matched against refs/heads
#    branches: [ main, develop ]
env:
  PROJECT: "best-practice"
  LENGUAGE: "java"
  ENVIROMENT_DEV: "development"
  ENVIROMENT_DEV_PREFIX: "dev"
  ENVIROMENT_INT: "integration"
  ENVIROMENT_INT_PREFIX: "int"
jobs:
  deploy:
    runs-on: [ancillaries, build]
    steps:
        # checkout source code in runner 
        - name: Checkout source
          uses: actions/checkout@v2
        # checkout source workflow action base in runner   
        - name: Checkout actions
          uses: actions/checkout@v2
          with:
            repository: 'Iberia-Ent/software-engineering--reference-architecture--workflow'
            token: ${{ secrets.TOKEN_REP }}
            ref: 'main'
            path: '.github/cicd'
        # Configure step build process    
        - name: build
          id: output-build
          uses: ./.github/cicd/github_actions/build
          with:
              project_name: ${{ env.PROJECT }}
              lenguage-code: ${{ env.LENGUAGE }}
              aws-access-key: ${{secrets.AWS_ACCESS_KEY}} 
              aws-secret-acesss-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              # active true repositorio codeartifact - required: true - default: false (nexus adopt)      
              # user registry artifact - if codeArtifact allow then user is owner aws id.
              codeartifact-allow: true
              repository-user: ${{secrets.CODEARTIFACT_OWNER}}                
              ### Disable because is codeArtifact
              # repository-host:  ${{secrets.nexus_url}}                  
              # repository-token: ${{secrets.nexus_key}}
          # Configure step build process    
        - name: environment
          uses: ./.github/cicd/github_actions/environment
          with:
              project_name: ${{ env.PROJECT }}
              service_name: ${{ steps.output-build.outputs.package-artifactid-name }}
              group_name:   ${{ steps.output-build.outputs.package-groupid-name }}
              aws-access-key: ${{ secrets.AWS_ACCESS_KEY }} 
              aws-secret-acesss-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-environment-name: ${{ env.ENVIROMENT_INT }}
              aws-environment-prefix: ${{ env.ENVIROMENT_INT_PREFIX }}
              aws-environment-dev-name: ${{ env.ENVIROMENT_DEV }}
              aws-environment-dev-prefix: ${{ env.ENVIROMENT_DEV_PREFIX }}
              
