name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: [self-hosted, ancillaries]
    name: Scan
    steps:
      - name: Building Artifact
      - name: Scan
    
