name: Releases

on:
  release:
    types:
      - created
jobs:
  build_artifact:
    name: Build Artifact
    runs-on: [self-hosted, ancillaries, ami]
    env:
      IBIS_NEXUS_REPO_USER: ${{ secrets.IBIS_NEXUS_REPO_USER }}
      IBIS_NEXUS_REPO_PASS: ${{ secrets.IBIS_NEXUS_REPO_PASS }}
      IBIS_PACT_BROKER_USERNAME: ${{ secrets.IBIS_PACT_BROKER_USERNAME }}
      IBIS_PACT_BROKER_PASSWORD: ${{ secrets.IBIS_PACT_BROKER_PASSWORD }}
      GITHUB_TOKEN_ENV: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      ARTIFACT_VERSION: ${{ env.ARTIFACT_VERSION }}
      MICROSERVICE_NAME: ${{ env.MICROSERVICE_NAME }}
      ARTIFACT_ID: ${{ env.ARTIFACT_ID }}
      ARTIFACT_GROUP_ID: ${{ env.ARTIFACT_GROUP_ID }}

    steps: 
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Checkout actions
      uses: actions/checkout@v2
      with:
        repository: 'Iberia-Ent/commercial--management--ancillaries--workflows'
        token: ${{ secrets.GH_PAT_CICD_ANCILLARIES }}
        ref: '1.0'
        path: '.github/cicd-ancillaries'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Maven 3.8.2
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.2
    
    - name: Build Artifact
      uses: ./.github/cicd-ancillaries/github_actions/ci/rlse/artifact

  build_docs:
    name: Build Documentations
    needs: [build_artifact]
    runs-on: [self-hosted, ancillaries, ami]
    env:
      IBIS_NEXUS_REPO_USER: ${{ secrets.IBIS_NEXUS_REPO_USER }}
      IBIS_NEXUS_REPO_PASS: ${{ secrets.IBIS_NEXUS_REPO_PASS }}
      GITHUB_TOKEN_ENV: ${{ secrets.GITHUB_TOKEN }}
      ARTIFACT_VERSION: ${{ needs.build_artifact.outputs.ARTIFACT_VERSION }}
      MICROSERVICE_NAME: ${{ needs.build_artifact.outputs.MICROSERVICE_NAME }}

    steps: 
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Checkout actions
      uses: actions/checkout@v2
      with:
        repository: 'Iberia-Ent/commercial--management--ancillaries--workflows'
        token: ${{ secrets.GH_PAT_CICD_ANCILLARIES }}
        ref: '1.0'
        path: '.github/cicd-ancillaries'
    
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build Docs
      uses: ./.github/cicd-ancillaries/github_actions/ci/rlse/docs

  build_ami:
    name: Build AMI
    needs: [build_artifact, build_docs]
    runs-on: [self-hosted, ancillaries, ami]
    env:
      ARTIFACT_VERSION: ${{ needs.build_artifact.outputs.ARTIFACT_VERSION }}
      MICROSERVICE_NAME: ${{ needs.build_artifact.outputs.MICROSERVICE_NAME }}
      ARTIFACT_ID: ${{ needs.build_artifact.outputs.ARTIFACT_ID }}
      ARTIFACT_GROUP_ID: ${{ needs.build_artifact.outputs.ARTIFACT_GROUP_ID }}
      AWS_ANCILLARIES_ACCESS_KEY_ID: ${{ secrets.AWS_ANCILLARIES_ACCESS_KEY_ID }}
      AWS_ANCILLARIES_SECRET_ACCESS_KEY: ${{ secrets.AWS_ANCILLARIES_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout actions
      uses: actions/checkout@v2
      with:
        repository: 'Iberia-Ent/commercial--management--ancillaries--workflows'
        token: ${{ secrets.GH_PAT_CICD_ANCILLARIES }}
        ref: '1.0'
        path: '.github/cicd-ancillaries'
    
    - name: Set up Packer 1.6.6
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.6.6

    - name: Build AMI
      uses: ./.github/cicd-ancillaries/github_actions/ci/rlse/ami
